add summer icon
Limych/ha-snowtire pull request #26
Opened 2021-04-22 11:42 UTC by phedoreanu

## Breaking change

## Proposed change

This PR adds support for changing the sensor's icon ❄️ and ☀️.

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (which adds functionality to an this integration)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example entry for `configuration.yaml`:

```yaml
# Example configuration.yaml

```

## Additional information

- This PR fixes or closes issue: fixes #25 
- This PR is related to issue:

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [x] The code has been formatted using Black (`black --fast custom_components`)

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated to README.md

2021-04-24 11:01 UTC, phedoreanu commented
@Limych hey dude, would you please approve the remaining workflows and merge this PR? 😀

2021-04-26 10:53 UTC, Limych commented
Thanks for your contribution to the project. The proposal is interesting, but there are a couple of notes, which see below.

2021-04-26 11:01 UTC, Limych requested changes

2021-04-26 11:01 UTC, Limych commented on custom_components/snowtire/binary_sensor.py
> +        return ICON_WINTER if self.is_on else ICON_SUMMER
I believe that it would be more correct to do the opposite logic: an icon for summer if the value is False, for winter - in other cases.

2021-04-26 11:01 UTC, Limych commented on tests/test_binary_sensor.py
> +    assert default_sensor.icon == ICON_SUMMER
This is a check for a default value. OK. (If we change the logic above, it should also be the other way around)

2021-04-26 11:01 UTC, Limych commented on tests/test_binary_sensor.py
> +    assert default_sensor.icon == ICON_WINTER
This is a test for True. OK.

In line 121, you must also insert this check. For consistency and not to confuse those who will write / read the code after us.

But there is no test for False.
It needs to be added. Line 147

2021-04-26 11:34 UTC, phedoreanu commented
Done. Please validate the workflows :)

2021-04-26 12:16 UTC, phedoreanu commented
The `mdi:snowflake` icon is kind of ugly. I was thinking of changing it to the snowman one. Or even make them configurable?

What do you think?

2021-04-26 12:36 UTC, Limych approved these changes

2021-04-26 12:45 UTC, Limych requested changes

2021-04-26 12:45 UTC, Limych commented on custom_components/snowtire/binary_sensor.py
> +        return ICON_SUMMER if not self.is_on else ICON_WINTER
Small bug. 😞  Need not `not self.is_on` but `self.is_on is False`.

2021-04-26 12:47 UTC, Limych commented
The snowflake icon looks like a similar icon in the car's display panel and on the tires themselves.  You shouldn't change it.  If the user wants, he can always change any icon of any sensor through the settings in HA.

2021-04-26 12:53 UTC, Limych approved these changes
Thank you ❤️

2021-04-26 12:53 UTC, merged

2021-05-02 21:32 UTC, phedoreanu commented
Any chance of a new release? 😀